name: Validate HACS

on:
  pull_request:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
